- hosts: terraform-ansible
task:
- name: criando o arquivo index
  copy:
    dest: /home/ubuntu/index.html
    content: <h1> Feito com terrafore e ansible </h1>
- name: criando o servidor
  sehll: "nohup busybox httpd -f -p 8080 &"    